{
 "title": "Hardware Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "All Jobs Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lustre Memory",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 3, "x": 3, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "system_memory_used_bytes{job=\"lustre\"}",
       "legendFormat": "{{Available Mem}}"
      },
      {
       "expr": "system_memory_available_bytes{job=\"lustre\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Chroma Memory",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 3, "x": 8, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "system_memory_used_bytes{job=\"chroma\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "system_memory_available_bytes{job=\"chroma\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "vLLM Memory",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 3, "x": 13, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "system_memory_used_bytes{job=\"vllm\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "system_memory_available_bytes{job=\"vllm\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Monitiors Memory",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 3, "x": 18, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "system_memory_used_bytes{job=\"monitors\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "system_memory_available_bytes{job=\"monitors\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Lustre CPU",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 3, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cpu_load_1m{job=\"lustre\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Chroma CPU",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 8, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cpu_load_1m{job=\"chroma\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "vLLM CPU",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 13, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cpu_load_1m{job=\"vllm\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Monitors CPU",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 3, "x": 18, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cpu_load_1m{job=\"monitors\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "ChromaDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chroma Memory Percentage All Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 1 },
     "targets": [
      {
       "expr": "system_memory_percent{job=\"chroma\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Chroma CPU Percentage All Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 41 },
     "targets": [
      {
       "expr": "cpu_load_1m{job=\"chroma\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Lustre IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lustre Memory Percentage All Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 3 },
     "targets": [
      {
       "expr": "system_memory_percent{job=\"lustre\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Lustre CPU Percentage All Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 27 },
     "targets": [
      {
       "expr": "cpu_load_1m{job=\"lustre\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Monitors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Monitors Memory Percentage All Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 4 },
     "targets": [
      {
       "expr": "system_memory_percent{job=\"monitors\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Monitors CPU Percentage All Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 12 },
     "targets": [
      {
       "expr": "cpu_load_1m{job=\"monitors\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "vLLM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "vLLM Memory Percentage All Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 5 },
     "targets": [
      {
       "expr": "system_memory_percent{job=\"vllm\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "vLLM CPU Percentage All Nodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 13 },
     "targets": [
      {
       "expr": "cpu_load_1m{job=\"vllm\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Complete Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "System Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 36 },
     "targets": [
      { "expr": "system_memory_percent", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "CPU Load 1M average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 44 },
     "targets": [
      { "expr": "cpu_load_1m", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}