configuration:
  target: "meluxina"

service:
  name: "qdrant-stress"
  type: "qdrant"
  partition: "cpu"
  nodes: 1
  time_limit: "01:00:00"
  settings:
    port: 6333

client:
  name: "qdrant-stress-client"
  type: "qdrant_stress"
  partition: "cpu"
  nodes: 1
  time_limit: "00:50:00"
  settings:
    collection: "benchmark"
    dim: 128
    num_points: 10000
    batch_size: 256
    num_queries: 1000
    top_k: 10
    warmup_delay: 15

benchmarks:
  num_clients: 4
  client_delay: 10
